Instead of checking for pread/pwrite, test whether we can use them.

diff --git a/mux/src/configure b/mux/src/configure
--- a/mux/src/configure
+++ b/mux/src/configure
@@ -1313,6 +1313,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
           ac_config_headers="$ac_config_headers autoconf.h"
 
+
 echo "$as_me:$LINENO: checking whether to enable Reality Levels" >&5
 echo $ECHO_N "checking whether to enable Reality Levels... $ECHO_C" >&6
 # Check whether --enable-realitylvls or --disable-realitylvls was given.
@@ -1323,8 +1324,8 @@ if test "${enable_realitylvls+set}" = set; then
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
     else
-      LIBS="-lstdc++"
       REALITY_LVLS="-DREALITY_LVLS"
+      LIBS="-lstdc++"
       REALITY_SRC="levels.cpp"
       REALITY_OBJ="levels.o"
       echo "$as_me:$LINENO: result: yes" >&5
@@ -1337,6 +1338,10 @@ else
 echo "${ECHO_T}no" >&6
 
 fi;
+
+
+
+
 
 echo "$as_me:$LINENO: checking whether to enable WOD Realms" >&5
 echo $ECHO_N "checking whether to enable WOD Realms... $ECHO_C" >&6
@@ -5686,9 +5691,7 @@ done
 
 
 
-
-
-for ac_func in gettimeofday select socket pread pwrite
+for ac_func in gettimeofday select socket
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -10307,6 +10310,62 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
+
+{ echo "$as_me:$LINENO: checking for pread and pwrite..." >&5
+echo "$as_me: checking for pread and pwrite..." >&6;}
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sys/types.h>
+#include <sys/uio.h>
+#include <unistd.h>
+main() { pwrite(0, "abc", 3, 0); exit(0); }
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pwrite_works=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+pwrite_works=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+if test $pwrite_works = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_PREAD 1
+_ACEOF
+
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_PWRITE 1
+_ACEOF
+
+fi
+
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
