Fix autoconf of ieeefp.h on FreeBSD.

diff --git a/mux/src/configure b/mux/src/configure
--- a/mux/src/configure
+++ b/mux/src/configure
@@ -5889,42 +5889,62 @@ fi
 rm -f conftest*
 
 if test $ac_cv_header_ieeefp_h = yes; then
-	cat >conftest.$ac_ext <<_ACEOF
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <ieeefp.h>
 
+    #include <ieeefp.h>
+
+int
+main ()
+{
+
+    int main(int argc, char *argv[])
+    {
+        fp_prec_t a = fpgetprec();
+        fpsetprec(FP_PD);
+        return 0;
+    }
+
+  ;
+  return 0;
+}
 _ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  $EGREP "fpsetprec" >/dev/null 2>&1; then
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
   cat >>confdefs.h <<\_ACEOF
-#define HAVE_FPSETPREC 1
+#define IEEEFP_H_USEABLE 1
 _ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
 fi
-rm -f conftest*
-
-	cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <ieeefp.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  $EGREP "fpgetprec" >/dev/null 2>&1; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_FPGETPREC 1
-_ACEOF
-
-fi
-rm -f conftest*
-
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 if test $ac_cv_header_fenv_h = yes; then
 	cat >conftest.$ac_ext <<_ACEOF
@@ -6817,7 +6837,6 @@ RETSIGTYPE sighand(int sig, int code)
 
 int main(int argc, char *argv[])
 {
-
   rlev = 0;
   signal(SIGCHLD, sighand);
   if (fork()) {
